version: "3.7"
services:
  terraform-utils:
    image: hashicorp/terraform:0.14.3
    env_file: .env
    environment:
      - AWS_SDK_LOAD_CONFIG=1
    entrypoint: ""
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
    working_dir: /work

  envvars:
    image: flemay/envvars:0.0.6
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work
